[package]
name = "bevy-pixels-web-game-poc"
version = "0.1.0"
edition = "2021"
rust-version = "1.68"
authors = ["Beetroot Paul <paul@beetrootpaul.com>"]
repository = "https://github.com/beetrootpaul/poc--bevy-pixels-web-game"
license = "MIT"
#TODO: any other fields?

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.11.0" # https://github.com/parasyte/pixels

# https://github.com/bevyengine/bevy
[dependencies.bevy]
version = "0.10.0"
# https://docs.rs/crate/bevy/latest/features
default-features = false
features = [
    "bevy_winit"
]
