[package]
name = "bevy-pixels-web-game-poc"
version = "0.1.0"
edition = "2021"
rust-version = "1.68"
authors = ["Beetroot Paul <paul@beetrootpaul.com>"]
repository = "https://github.com/beetrootpaul/poc--bevy-pixels-web-game"
license = "MIT"
#TODO: any other fields?

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
