#[allow(dead_code)]
pub enum FontGlyph {
    None,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Colon,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
}

impl FontGlyph {
    pub fn of(char: char) -> FontGlyph {
        match char {
            '0' => FontGlyph::Digit0,
            '1' => FontGlyph::Digit1,
            '2' => FontGlyph::Digit2,
            '3' => FontGlyph::Digit3,
            '4' => FontGlyph::Digit4,
            '5' => FontGlyph::Digit5,
            '6' => FontGlyph::Digit6,
            '7' => FontGlyph::Digit7,
            '8' => FontGlyph::Digit8,
            '9' => FontGlyph::Digit9,
            ':' => FontGlyph::Colon,
            'A' => FontGlyph::A,
            'B' => FontGlyph::B,
            'C' => FontGlyph::C,
            'D' => FontGlyph::D,
            'E' => FontGlyph::E,
            'F' => FontGlyph::F,
            'G' => FontGlyph::G,
            'H' => FontGlyph::H,
            'I' => FontGlyph::I,
            'J' => FontGlyph::J,
            'K' => FontGlyph::K,
            'L' => FontGlyph::L,
            'M' => FontGlyph::M,
            'N' => FontGlyph::N,
            'O' => FontGlyph::O,
            'P' => FontGlyph::P,
            'Q' => FontGlyph::Q,
            'R' => FontGlyph::R,
            'S' => FontGlyph::S,
            'T' => FontGlyph::T,
            'U' => FontGlyph::U,
            'V' => FontGlyph::V,
            'W' => FontGlyph::W,
            'X' => FontGlyph::X,
            'Y' => FontGlyph::Y,
            'Z' => FontGlyph::Z,
            _ => FontGlyph::None,
        }
    }
}
