name: "clippy"

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  clippy:
    strategy:
      # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
      fail-fast: false
      # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy
      matrix:
        command_variant:
          - cache_sub_key: "variant-default"
            lint_flags: "-D warnings"
            params: ""
          - cache_sub_key: "variant-vis-main"
            lint_flags: "-D warnings"
            params: "--features visualize_schedule_main"
          - cache_sub_key: "variant-vis-fixed"
            lint_flags: "-D warnings"
            params: "--features visualize_schedule_fixed_update"
          - cache_sub_key: "variant-release"
            lint_flags: "-D warnings -A dead_code -A unused-imports -A unused_mut -A unused-variables"
            params: "--release"
          - cache_sub_key: "variant-wasm32"
            lint_flags: "-D warnings"
            params: "--target wasm32-unknown-unknown"
          - cache_sub_key: "variant-wasm32-release"
            lint_flags: "-D warnings -A dead_code -A unused-imports -A unused_mut -A unused-variables"
            params: "--target wasm32-unknown-unknown --release"
          - cache_sub_key: "test"
            lint_flags: "-D warnings"
            params: "--profile test"
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
      - uses: ./.github/shared-steps
      # --features bevy/x11: we need Bevy's support for X11 in GitHub Actions on Ubuntu
      - run: cargo clippy --features bevy/x11 ${{ matrix.command_variant.params }} -- ${{ matrix.command_variant.lint_flags }}
